version: '3.7'

services: 
  redis_master:
    image: redis
    environment: 
      - MASTER=1
      - IP=10.1.17.29
      - PORT=6379
      - CLUSTER_NAME=redis-cluster
      - QUORUM=2
      - PORT_SENTINEL=26379
    volumes: 
      - redis_master:/data
      - ./redis/:/root/
      - ./log/master:/var/log/redis
    ports: 
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 1G
    networks: 
      bdt_network:
        ipv4_address: 10.1.17.29
    command: /bin/bash -c "cd /root/config; /bin/bash ./init.sh; tail -f /dev/null"

  redis_slave_1:
    image: redis
    environment: 
      - MASTER=0
      - MASTER_IP=10.1.17.29
      - MASTER_PORT=6379
      - CLUSTER_NAME=redis-cluster
      - QUORUM=2
      - IP=10.1.17.30
      - PORT=6379
      - PORT_SENTINEL=26379
    volumes: 
      - redis_slave_1:/data
      - ./redis/:/root/
      - ./log/slave_1:/var/log/redis
    ports: 
      - "6380:6379"
    deploy:
      resources:
        limits:
          memory: 1G
    networks: 
      bdt_network:
        ipv4_address: 10.1.17.30
    command: /bin/bash -c "cd /root/config; /bin/bash ./init.sh; tail -f /dev/null"

  redis_slave_2:
    image: redis
    environment: 
      - MASTER=0
      - MASTER_IP=10.1.17.29
      - MASTER_PORT=6379
      - CLUSTER_NAME=redis-cluster
      - QUORUM=2
      - IP=10.1.17.31
      - PORT=6379
      - PORT_SENTINEL=26379
    volumes: 
      - redis_slave_2:/data
      - ./redis/:/root/
      - ./log/slave_2:/var/log/redis
    ports: 
      - "6381:6379"
    deploy:
      resources:
        limits:
          memory: 1G
    networks: 
      bdt_network:
        ipv4_address: 10.1.17.31
    command: /bin/bash -c "cd /root/config; /bin/bash ./init.sh; tail -f /dev/null"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      bdt_network:
        ipv4_address: 10.1.17.32
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - mysql:/var/lib/mysql
  
  wordpress:
    build: ./wordpress
    volumes: 
      - wordpress:/var/www
      - ./wordpress/log:/var/log/apache2
      - ./wordpress/root:/root
    environment:
      - DB_HOST=10.1.17.32
      - DB_NAME=wordpress
      - DB_USER=root
      - DB_PASSWORD=password
      - FTP_USER=root
      - FTP_PASS=password
      - FTP_HOST='localhost:8022'
    depends_on: 
      - mysql
    deploy:
      resources:
        limits:
          memory: 1G
    networks: 
      bdt_network:
        ipv4_address: 10.1.17.33
    ports: 
      - "80:80"
      - "8022:22"
    command: /bin/bash -c "/bin/bash /root/startup.sh; tail -f /dev/null"

volumes: 
  redis_master: {}
  redis_slave_1: {}
  redis_slave_2: {}
  wordpress: {}
  mysql: {}

networks:
  bdt_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.17.0/24